---
services:
  # azurite:
  #   image: mcr.microsoft.com/azure-storage/azurite
  #   container_name: "azurite"
  #   hostname: azurite
  #   restart: always
  #   ports:
  #     - "10000:10000"  # blob
  #     - "10001:10001"  # queue
  #     - "10002:10002"  # table
  portfolio_parser:
    build:
      context: portfolio_parser
    volumes:
      - type: bind
        source: mounts/processed_portfolios
        target: /mnt/processed_portfolios
      - type: bind
        source: mounts/raw_portfolios
        target: /mnt/raw_portfolios
    # tty: true
    # stdin_open: true
    # command: ["bash"]
    environment:
      USERID: FAKEUSER
  report_runner:
    build:
      context: report_runner
    volumes:
      - type: bind
        source: mounts/processed_portfolios
        target: /mnt/processed_portfolios
      - type: bind
        source: mounts/reports
        target: /mnt/reports
    # tty: true
    # stdin_open: true
    # command: ["bash"]
    environment:
      PORTFOLIO: 280f7115-b6a6-4d4b-8fad-40c485ca561e
